"""Change image columns to Text

Revision ID: 407c0b882509
Revises: 66acaa3eb7cd
Create Date: 2024-07-12 18:31:55.517666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407c0b882509'
down_revision = '66acaa3eb7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('image',
                existing_type=sa.VARCHAR(length=120),
                type_=sa.Text(),
                existing_nullable=True)
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('image',
                existing_type=sa.VARCHAR(length=120),
                type_=sa.Text(),
                existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(length=1000000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(length=1000000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
