"""empty message

Revision ID: 45155601183d
Revises: 95bb460fc156
Create Date: 2024-07-09 15:10:45.700288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45155601183d'
down_revision = '95bb460fc156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('room_count')

    # ### end Alembic commands ###
