"""Add username to Review model

Revision ID: aaded0b227e6
Revises: 407c0b882509
Create Date: 2024-07-27 10:33:29.331434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaded0b227e6'
down_revision = '407c0b882509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.execute("UPDATE review SET username = 'unknown' WHERE username IS NULL")
        batch_op.alter_column('username', nullable=False)
        batch_op.drop_constraint('review_room_id_fkey', type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('review_room_id_fkey', 'room', ['room_id'], ['id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
